@startuml 画面遷移図



left to right direction
title 画面遷移図 ver1.1

state タイトル

タイトル : レベル1
タイトル : レベル2
タイトル : レベル3

クイズ画面 : 問題画面JPG
クイズ画面 : 問題文
クイズ画面 : 入力フォーム
クイズ画面 : 回答ボタン

' クイズ画面2 : 問題画面JPG
' クイズ画面2 : 問題文
' クイズ画面2 : 入力欄
' クイズ画面2 : 回答(B)
' クイズ画面2 : タイトル(B)
' クイズ画面2 : OS切り替え


解答画面 : 解答画像GIF
解答画面 : 解答ショトカ
解答画面 : 次の問題

全回答後画面 : 得点表示




タイトル --> クイズ画面 : レベル1-3
クイズ画面 --> 解答画面 : 回答
解答画面 --> クイズ画面 : 次の問題(問題更新)
解答画面 --> 全回答後画面 : 得点確認
@enduml