@startuml 画面遷移図



left to right direction
title 画面遷移図 ver0.1

state タイトル

タイトル : レベル1(B)
タイトル : レベル2(B)
タイトル : レベル3(B)
タイトル : ショトカ一覧(B)
タイトル : ランキング(B)

クイズ画面 : 問題画面JPG
クイズ画面 : 問題文
クイズ画面 : 入力ボタン
クイズ画面 : 回答(B)
クイズ画面 : タイトル(B)
クイズ画面 : OS切り替え

クイズ画面2 : 問題画面JPG
クイズ画面2 : 問題文
クイズ画面2 : 入力欄
クイズ画面2 : 回答(B)
クイズ画面2 : タイトル(B)
クイズ画面2 : OS切り替え


解答画面 : 解答画像GIF
解答画面 : 解答ショトカ(上から推奨順)
解答画面 : 問題再確認(B)
解答画面 : 次の問題(B)
解答画面 : タイトル(B)
解答画面 : 得点確認(B:if no 次の問題)

全回答後画面 : 正誤履歴
全回答後画面 : 得点
全回答後画面 : ショトカ一覧(B)




ショトカ一覧 : ショトカ
ショトカ一覧 : ショトカ詳細

タイトル --> クイズ画面 : レベル1-3
タイトル --> ショトカ一覧 : ショトカ一覧
クイズ画面 --> 解答画面 : 回答
解答画面 --> クイズ画面2 : 次の問題
解答画面 --> 全回答後画面 : 得点確認
全回答後画面 --> ショトカ一覧 : ショトカ一覧
@enduml