' alt+DでER図表示

@startuml shortcut_quiz

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho


entity "ver 0.8.2" {

}

entity "users" {
    *id <generated> : Integer
    --
    *id_on_twitch: String
    *login_name : String
    *display_name: String
    *profile_image_url: String
    *user_created_at: String

    *created_at : datetime
    *updated_at : datetime
}


entity "playlists" {
    *id <generated> : Integer
    --
    *user_id <FK>
    *name : String
    *published :Boolean

    *created_at : Date
    *updated_at : Date
}


entity "clips" {
    *id <generated> : Integer(LIB上管理ID)
    --
    *id_on_twitch : String (Twitch上管理ID)
    *url : String
    *embed_url : String
    *broadcaster_id : String
    *broadcaster_name : String
    *creator_id : String
    *creator_name : String
    *video_id : String
    *game_id : String (Twitch上管理ID)
    *language : String
    *title : String
    *view_count : Integer
    *clip_created_at : Date
    *thumbnail_url: String
    *duration : float
    *vod_offset : Integer
    *is_featured : Boolean

    *created_at : datetime
    *updated_at : datetime
}


entity  "playlist_clips" {
    *id <generated> : Integer
    --
    *playlist_id <FK>
    *clip_id <FK>
    --
    *order_index : Integer

    *created_at : datetime
    *updated_at : datetime
}
entity "user_favorite_playlists" {
    *id <generated> : Integer
    --
    *user_id <FK>
    *playlist_id <FK>
    --
    *order_index : Integer

    *created_at : datetime
    *updated_at : datetime
}

entity "daily_highlight_playlists" {
    デモだと不要
    *id <generated> : Integer
    --
    *playlist_id <FK>
    *start_date : Date

    *created_at : datetime
    *updated_at : datetime
}
entity "weekly_highlight_playlists" {
    デモだと不要
    *id <generated> : Integer
    --
    *playlist_id <FK>
    *start_date : Date
    *end_date : Date

    *created_at : datetime
    *updated_at : datetime
}
entity "monthly_highlight_playlists" {
    デモだと不要
    *id <generated> : Integer
    --
    *playlist_id <FK>
    *start_date : Date
    *end_date : Date

    *created_at : datetime
    *updated_at : datetime
}

entity "games" {
  *id <generated> : Integer (LIB上管理ID)
  --
  *game_id : Integer (Twitch上管理ID)
  *game_title :String
  *game_thumbnail_url: String
}

entity "broadcasters"{
  *id <generated> : Integer (LIB上管理ID)
  --
  *broadcaster_id : Integer (Twitch上管理ID)
  *profile_image_url : String
  *(broadcaster_name)*いらない
}

' entity  "follow_broadcasters"{
'   *user_id <FK>
'   *broadcaster_id <FK>
' }


users||--|{playlists
playlists||--|{playlist_clips
playlist_clips}|--||clips
users||--|{user_favorite_playlists
user_favorite_playlists}|--||playlists

daily_highlight_playlists}|--||playlists
weekly_highlight_playlists}|--||playlists
monthly_highlight_playlists}|--||playlists

games||--|{clips

broadcasters||--|{clips

' users||--|{follow_broadcasters
' follow_broadcasters}|--||broadcasters


@enduml


' entity "users_follow_broadcasters" {
'     *follow_broadcaster_id :Integer(API取得はstr)
'     --
'     *follow_broadcaster_login : String
'     *follow_broadcaster_name : String
'     *followed_at : String

'     *user_id <FK>
' }


' entity "playlists_tags" {
'     *playlist_id <FK>
'     --
'     *tag_id <FK>
' }

' entity "tags" {
'     *tag_id <generated>
'     *tag_name : String
' }

' users||--|{users_follow_broadcasters
' playlists||--|{playlists_tags
' playlists_tags}|--||tags


' clip
'     *clip_id <generated> : Integer(LIB上管理ID)
'     --
' 以下API取得情報
'     *id_on_twtich : String (Twitch上管理ID)
'     *url : String
'     *embed_url : String
'     *broadcaster_id : String
'     *broadcaster_name : String
'     *creator_id : String
'     *creator_name : String
'     *video_id : String
'     *language : String
'     *title : String
'     *view_count : Integer
'     *created_at : String
'     *duration : float
'     *vod_offset : Integer
'     *is_featured : Boolean
'     *game_id : String
'     *game_title : String (別でAPI叩く必要有)
