' alt+DでER図表示

@startuml shortcut_quiz

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho


entity "ver 0.4.0" {

}

entity "users" {
    *user_id (?)<generated> : Integer
    --
    *name: String
    *token(?) : String
    *API取得情報 省略
}


entity "playlists" {
    *playlist_id <generated> : Integer
    --
    *user_id <FK>
    *name : String
    *favorite_count : Integer
    *published :Boolean
    *created_at : Date
    *update_at : Date
}


entity "clips" {
    *clip_id <generated> : Integer(LIB上管理ID)
    --
以下API取得情報
    *tw_id : String (Twitch上管理ID)
    *url : String
    *embed_url : String
    *broadcaster_id : String
    *broadcaster_name : String
    *creator_id : String
    *creator_name : String
    *video_id : String
    *language : String
    *title : String
    *view_count : Integer
    *created_at : String
    *duration : float
    *vod_offset : Integer
    *is_featured : Boolean
    *game_id : String
    *game_title : String (別でAPI叩く必要有)
    ' *pagination : Object
}

entity  "playlist_clips" {
    *add_id <generated> : Integer
    --
    *playlist_id <FK>
    *clip_id <FK>
    --
    *order_index : Integer
    *add_datetime : Date
}
entity "user_favorite_playlists" {
    *favorite_id <generated> : Integer
    --
    *user_id <FK>
    *playlist_id <FK>
    --
    *order_index : Integer
    *favorite_datetime : Date
}

entity "daily_highlight_playlists" {
    *daily_id <generated> : Integer : Integer
    --
    *playlist_id <FK>
    *created_at : Date
    *period : (Date~Date)?
}
entity "weekly_highlight_playlists" {
    *weekly_id <generated> : Integer : Integer
    --
    *playlist_id <FK>
    *created_at : Date
    *period : (Date~Date)?
}
entity "monthly_highlight_playlists" {
    *monthly_id <generated> : Integer : Integer
    --
    *playlist_id <FK>
    *created_at : Date
    *period : (Date~Date)?
}



' entity "users_follow_broadcasters" {
'     *follow_broadcaster_id :Integer(API取得はstr)
'     --
'     *follow_broadcaster_login : String
'     *follow_broadcaster_name : String
'     *followed_at : String

'     *user_id <FK>
' }


' entity "playlists_tags" {
'     *playlist_id <FK>
'     --
'     *tag_id <FK>
' }

' entity "tags" {
'     *tag_id <generated>
'     *tag_name : String
' }

users||--|{playlists
playlists||--|{playlist_clips
playlist_clips}|--||clips
users||--|{user_favorite_playlists
user_favorite_playlists}|--||playlists

daily_highlight_playlists}|--||playlists
weekly_highlight_playlists}|--||playlists
monthly_highlight_playlists}|--||playlists





' users||--|{users_follow_broadcasters
' playlists||--|{playlists_tags
' playlists_tags}|--||tags


@enduml

